#!/bin/bash

curl https://images.ladepeche.fr/api/v1/images/view/5c35f9568fe56f169110554e/large/image.jpg > ~/background.png

gsettings set org.gnome.desktop.background picture-uri "file:///home/${USER}/background.png"

gsettings set org.gnome.desktop.background picture-uri-dark "file:///home/${USER}/background.png"